/*
 * Port_cfg.h
 *
 *  Created on: Jun 20, 2023
 *      Author: Nadim
 */

#ifndef PORT_CFG_H_
#define PORT_CFG_H_

#define PORTA_PIN0_DIR			INPUT
#define PORTA_PIN1_DIR			INPUT
#define PORTA_PIN2_DIR			INPUT
#define PORTA_PIN3_DIR			INPUT
#define PORTA_PIN4_DIR			INPUT
#define PORTA_PIN5_DIR			INPUT
#define PORTA_PIN6_DIR			INPUT
#define PORTA_PIN7_DIR			INPUT


#define PORTB_PIN0_DIR			INPUT
#define PORTB_PIN1_DIR			INPUT
#define PORTB_PIN2_DIR			INPUT
#define PORTB_PIN3_DIR			INPUT
#define PORTB_PIN4_DIR			INPUT
#define PORTB_PIN5_DIR			INPUT
#define PORTB_PIN6_DIR			INPUT
#define PORTB_PIN7_DIR			INPUT


#define PORTC_PIN0_DIR			INPUT
#define PORTC_PIN1_DIR			INPUT
#define PORTC_PIN2_DIR			INPUT
#define PORTC_PIN3_DIR			INPUT
#define PORTC_PIN4_DIR			INPUT
#define PORTC_PIN5_DIR			INPUT
#define PORTC_PIN6_DIR			INPUT
#define PORTC_PIN7_DIR			INPUT


#define PORTD_PIN0_DIR			INPUT
#define PORTD_PIN1_DIR			INPUT
#define PORTD_PIN2_DIR			INPUT
#define PORTD_PIN3_DIR			INPUT
#define PORTD_PIN4_DIR			INPUT
#define PORTD_PIN5_DIR			INPUT
#define PORTD_PIN6_DIR			INPUT
#define PORTD_PIN7_DIR			INPUT



#define PORTA_PIN0_VAL			FLOATING
#define PORTA_PIN1_VAL			FLOATING
#define PORTA_PIN2_VAL			FLOATING
#define PORTA_PIN3_VAL			FLOATING
#define PORTA_PIN4_VAL			FLOATING
#define PORTA_PIN5_VAL			FLOATING
#define PORTA_PIN6_VAL			FLOATING
#define PORTA_PIN7_VAL			FLOATING


#define PORTB_PIN0_VAL			FLOATING
#define PORTB_PIN1_VAL			FLOATING
#define PORTB_PIN2_VAL			FLOATING
#define PORTB_PIN3_VAL			FLOATING
#define PORTB_PIN4_VAL			FLOATING
#define PORTB_PIN5_VAL			FLOATING
#define PORTB_PIN6_VAL			FLOATING
#define PORTB_PIN7_VAL			FLOATING


#define PORTC_PIN0_VAL			FLOATING
#define PORTC_PIN1_VAL			FLOATING
#define PORTC_PIN2_VAL			FLOATING
#define PORTC_PIN3_VAL			FLOATING
#define PORTC_PIN4_VAL			FLOATING
#define PORTC_PIN5_VAL			FLOATING
#define PORTC_PIN6_VAL			FLOATING
#define PORTC_PIN7_VAL			FLOATING


#define PORTD_PIN0_VAL			FLOATING
#define PORTD_PIN1_VAL			FLOATING
#define PORTD_PIN2_VAL			FLOATING
#define PORTD_PIN3_VAL			FLOATING
#define PORTD_PIN4_VAL			FLOATING
#define PORTD_PIN5_VAL			FLOATING
#define PORTD_PIN6_VAL			FLOATING
#define PORTD_PIN7_VAL			FLOATING

#endif /* PORT_CFG_H_ */
